/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GCom.java
 *
 * Created on Dec 16, 2013, 12:35:55 PM
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author ens13pps
 */
public class GCom extends javax.swing.JFrame {

    /** Creates new form GCom */
    public GCom() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenu = new javax.swing.JMenuBar();
        mnuFileMenu = new javax.swing.JMenu();
        mnuNewGroup = new javax.swing.JMenuItem();
        mnuConnectToRegistry = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuFileMenu.setText("File");

        mnuNewGroup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuNewGroup.setText("New Group");
        mnuFileMenu.add(mnuNewGroup);

        mnuConnectToRegistry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mnuConnectToRegistry.setText("Connect To Registry");
        mnuConnectToRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConnectToRegistryActionPerformed(evt);
            }
        });
        mnuFileMenu.add(mnuConnectToRegistry);

        mainMenu.add(mnuFileMenu);

        mnuEdit.setText("Edit");
        mainMenu.add(mnuEdit);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void mnuConnectToRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConnectToRegistryActionPerformed
        Object input = JOptionPane.showInputDialog(this, "Please enter the port", "Port", JOptionPane.QUESTION_MESSAGE, null, new String[]{"1099"}, "1099");
        
}//GEN-LAST:event_mnuConnectToRegistryActionPerformed
private
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GCom().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenuItem mnuConnectToRegistry;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuFileMenu;
    private javax.swing.JMenuItem mnuNewGroup;
    // End of variables declaration//GEN-END:variables
}
